services:
  db:
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_DB=db
    - USERMAP_UID=1000
    - USERMAP_GID=1000
    image: akretion/voodoo-postgresql
    volumes:
    - .db/data/:/var/lib/postgresql/data
    - .db/socket/:/var/run/postgresql/
  mailcatcher:
    image: akretion/lightweight-mailcatcher
    ports:
    - 1280:1080
    - 1225:1025
  odoo:
    environment:
    - PYTHONDONTWRITEBYTECODE=True
    extends:
      file: docker-compose.yml
      service: odoo
    links:
    - db
    ports:
    - 8069:8069
    - 8072:8072
    - 8032:5432
    volumes:
    - .:/workspace
    - .db/socket/:/var/run/postgresql/
    - /home/sylvain/.voodoo/shared:/home/sylvain/.voodoo/shared
    - /pro/grap/backup/:/workspace/backup/
version: '2'
